apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-nov7-4-gh 
  janus-idp.io/tekton: rag-nov7-4-gh
  backstage.io/kubernetes-id: rag-nov7-4-gh
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag-nov7-4-gh
resources: 
- application-dev.yaml